services:
    php:
        build: ./docker/php
        container_name: symfony_php
        working_dir: /var/www/html
        volumes:
            - ./backend:/var/www/html:delegated
            - type: tmpfs
              target: /var/www/html/var/cache
        environment:
            APP_ENV: dev
            MYSQL_HOST: db
            MYSQL_PORT: 3306
            MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
            - '80:80'
        volumes:
            - ./backend:/var/www/html:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: symfony_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d

    phpmyadmin:
        container_name: pma
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
        ports:
            - '8080:80'
        depends_on:
            - db

    frontend:
        image: node:20-alpine
        container_name: react_front
        working_dir: /app
        volumes:
            - ./frontend:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - '5173:5173'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=100

volumes:
    db_data:
