services:
    php:
        build: ./docker/php
        container_name: symfony_php
        volumes:
            - ./backend:/var/www/html:cached
        environment:
            APP_ENV: dev
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
            - '80:80'
        volumes:
            - ./backend:/var/www/html:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: symfony_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
        volumes:
            - db_data:/var/lib/mysql

    frontend:
        image: node:20-alpine
        container_name: react_front
        working_dir: /app
        volumes:
            - ./frontend:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - '5173:5173'

volumes:
    db_data:
